import{S as v,a as y,i as u}from"./assets/vendor-2618a76b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();let x=new v(".gallery-item a",{captionDelay:250,captionsData:"alt"});const m=document.querySelector(".gallery"),h=document.querySelector(".search-form"),a=document.querySelector(".load-btn"),c=document.querySelector(".loader");y.defaults.baseURL="https://pixabay.com/api";const q="42139525-c14302dd397ed074e72a8f596";let l=1,k="",d=0;h.addEventListener("submit",S);async function S(t){t.preventDefault(),m.innerHTML="",l=1,a.classList.add("is-hidden");const r=t.currentTarget.elements.query.value.trim();if(!r){p();return}try{const{hits:o,total:n}=await f(r);c.style.display="none",d=Math.ceil(n/15),o.length===0?(a.classList.add("is-hidden"),p()):(g(o),a.classList.remove("is-hidden"),a.addEventListener("click",w))}catch{}finally{h.reset(),l===d&&(a.classList.add("is-hidden"),u.error({maxWidth:432,position:"topRight",color:"red",message:"We're sorry, but you've reached the end of search results!"}))}}async function f(t,r){return c.style.display="block",y.get("/",{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}}).then(({data:o})=>o)}async function w(){l+=1;try{a.classList.add("is-hidden");const{hits:t}=await f(k,l);c.style.display="none",g(t),M(),a.classList.remove("is-hidden")}catch(t){console.log(t)}finally{l===d&&(a.classList.add("is-hidden"),u.error({maxWidth:432,position:"topRight",color:"red",message:"We're sorry, but you've reached the end of search results!"}))}}function g(t){const r=t.map(({webformatURL:o,largeImageURL:n,tags:e,likes:s,views:i,comments:L,downloads:b})=>`<li class="gallery-item">
            <a href=${n}> 
                <img class="gallery-image" src=${o} alt=${e} />
            </a>
            <div class="gallery-text">
                <p class="text-block">Likes: <span class="text-value">${s}</span></p>
                <p class="text-block">Views: <span class="text-value">${i}</span></p>
                <p class="text-block">Comments: <span class="text-value">${L}</span></p>
                <p class="text-block">Downloads: <span class="text-value">${b}</span></p>
            </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),x.refresh()}function M(){const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,left:0,behavior:"smooth"})}function p(){u.error({maxWidth:432,position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),c.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
