import{S as x,a as m,i as p}from"./assets/vendor-2618a76b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();let k=new x(".gallery-item a",{captionDelay:250,captionsData:"alt"});const h=document.querySelector(".gallery"),f=document.querySelector(".search-form"),o=document.querySelector(".load-btn"),d=document.querySelector(".loader");m.defaults.baseURL="https://pixabay.com/api";const q="42139525-c14302dd397ed074e72a8f596";let n=1,c="",u=0;f.addEventListener("submit",S);async function S(t){if(t.preventDefault(),h.innerHTML="",n=1,o.classList.add("is-hidden"),c=t.currentTarget.elements.query.value.trim(),!c){y();return}try{const{hits:r,total:a}=await g(c);d.style.display="none",u=Math.ceil(a/15),r.length===0?(o.classList.add("is-hidden"),y()):(L(r),o.classList.remove("is-hidden"),o.addEventListener("click",w))}catch{}finally{f.reset(),n===u&&(o.classList.add("is-hidden"),p.error({maxWidth:432,position:"topRight",color:"red",message:"We're sorry, but you've reached the end of search results!"}))}}async function g(t,r){return d.style.display="block",m.get("/",{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}}).then(({data:a})=>a)}async function w(){n+=1;try{o.classList.add("is-hidden");const{hits:t}=await g(c,n);d.style.display="none",L(t),M(),o.classList.remove("is-hidden")}catch(t){console.log(t)}finally{n===u&&(o.classList.add("is-hidden"),p.error({maxWidth:432,position:"topRight",color:"red",message:"We're sorry, but you've reached the end of search results!"}))}}function L(t){const r=t.map(({webformatURL:a,largeImageURL:l,tags:e,likes:s,views:i,comments:b,downloads:v})=>`<li class="gallery-item">
            <a href=${l}> 
                <img class="gallery-image" src=${a} alt=${e} />
            </a>
            <div class="gallery-text">
                <p class="text-block">Likes: <span class="text-value">${s}</span></p>
                <p class="text-block">Views: <span class="text-value">${i}</span></p>
                <p class="text-block">Comments: <span class="text-value">${b}</span></p>
                <p class="text-block">Downloads: <span class="text-value">${v}</span></p>
            </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",r),k.refresh()}function M(){const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,left:0,behavior:"smooth"})}function y(){p.error({maxWidth:432,position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),d.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
